import argparse
import glob
import logging
from pathlib import Path
from typing import Union

import numpy as np
import pandas as pd
import plotnine
from jinja2 import Environment, FileSystemLoader
from sklearn.metrics import auc

from detection.app.utils.loggingutils import initialize_logging
from detection.config import load_dataset_config
from detection.scripts import relative_to_absolute_path

REPORT_AGG_TEMPLATE = Path(__file__).parent.parent / 'templates'


def _parse_arguments() -> argparse.Namespace:
    """
    Parses the command line arguments.
    :return: Parsed arguments
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--dir-in", help="input directory with reporter results",
                        type=relative_to_absolute_path, required=True)
    parser.add_argument("-o", "--dir-out", help="output directory with output figures",
                        type=relative_to_absolute_path, required=True)
    parser.add_argument("-t", "--type", help="type of reporter",
                        choices=['allele', 'gene'], default='gene')
    parser.add_argument("-l", "--list-of-tools", help="selection of tools to include, default=all", nargs='+',
                        choices=['Argo', 'ARGpore2', 'KMA', 'DeepARG', 'ShortBRED'],
                        default=['Argo', 'ARGpore2', 'KMA', 'DeepARG', 'ShortBRED'])
    return parser.parse_args()


def _check_arguments() -> None:
    """
    Checks if the provided command line arguments are valid, raises an exception otherwise.
    :return: None
    """
    pass


def _retrieve_statistics_information(arguments: argparse.Namespace,
                                     datasets_configuration: dict = None) -> pd.DataFrame:
    """
    Retrieves statistics information from the statistics_summary files generated by the reporter.
    :param arguments: Command line arguments
    :param datasets_configuration: Datasets configuration for clean name and chemistry
    :return: Pandas dataframe of statistics information by dataset
    """
    mock_correspondence = {}
    chemistry_correspondence = {}
    level = arguments.type
    if datasets_configuration is not None:
        mock_correspondence = {name: datasets_configuration[name]['clean_name'] for name in
                               datasets_configuration.keys()}
        chemistry_correspondence = {name: datasets_configuration[name]['chemistry'] for name in
                                    datasets_configuration.keys()}

    directory_report = Path(f'reporter_{level}')
    statistics_files = glob.glob(str(Path(arguments.dir_in) / '*' / directory_report / 'statistics_summary.tsv'))
    output_dictionary = {}
    for stat_file in [Path(stat_file_path) for stat_file_path in statistics_files]:
        with open(stat_file) as handle:
            all_lines = handle.readlines()
        stat_dataframe = pd.DataFrame([x.strip().split('\t') for x in all_lines[1:]],
                                      columns=['tool', 'info', 'value']).to_dict('records')
        dataset = stat_file.parent.parent.stem
        chemistry = 'R9'
        try:
            chemistry = chemistry_correspondence[dataset]
            dataset = mock_correspondence[dataset]
        except KeyError:
            pass
        if dataset not in output_dictionary:
            output_dictionary[dataset] = {level: {}, 'Chemistry': chemistry}
        for stat in ['Precision', 'Recall', 'F1 score']:
            if stat not in output_dictionary[dataset][level]:
                output_dictionary[dataset][level][stat] = {f'{row["tool"]}': row['value'] for row in stat_dataframe
                                                           if row['info'] == stat}
            else:
                to_update = {f'{row["tool"]}': row['value'] for row in stat_dataframe
                             if row['info'] == stat}
                output_dictionary[dataset][level][stat].update(to_update)
    data_list = []
    for dataset in output_dictionary.keys():
        for stat in output_dictionary[dataset][level].keys():
            for tool in output_dictionary[dataset][level][stat].keys():
                if tool in arguments.list_of_tools:
                    data_list.append([dataset, level, stat, tool,
                                      output_dictionary[dataset][level][stat][tool],
                                      output_dictionary[dataset]['Chemistry']])

    final_statistics_df = pd.DataFrame(data_list, columns=['dataset', 'level', 'stat', 'tool', 'value', 'Chemistry'])
    final_statistics_df["value"] = pd.to_numeric(final_statistics_df["value"])
    return final_statistics_df


def _plot_aggregated_metrics_boxplot(metrics_df: pd.DataFrame, arguments: argparse.Namespace) -> dict[str, Path]:
    """
    Plots the aggregated metrics boxplot.
    :param metrics_df: previously generated dataframe
    :param arguments: Command line arguments
    :return: Dict with location to the boxplot graph PNG
    """
    color_mapping = 'dataset'
    output_figure_directory = arguments.dir_out / 'figures'
    if not output_figure_directory.exists():
        output_figure_directory.mkdir(parents=True, exist_ok=True)
    output_figure_path = Path(f'{arguments.dir_out}/figures/aggregated_boxplot.png')

    metrics_df['stat'] = pd.Categorical(metrics_df['stat'], categories=['Precision', 'Recall', 'F1 score'])
    p = plotnine.ggplot(metrics_df, plotnine.aes(x='factor(tool)', y='value'))
    p += plotnine.geom_boxplot(outlier_shape="")
    p += plotnine.geom_jitter(plotnine.aes(fill=color_mapping, color=color_mapping, shape='Chemistry'), size=2,
                              width=0.4)
    p += plotnine.theme(axis_text_x=plotnine.element_text(angle=45, hjust=1), figure_size=(8, 4))
    p += plotnine.scale_y_continuous(limits=(0, 1))
    p += plotnine.facet_wrap("stat")
    p += plotnine.labs(title="Aggregated metrics for each tool across all datasets.", x='Tool', y='Value',
                       fill=color_mapping.capitalize(), color=color_mapping.capitalize())
    if len(metrics_df['Chemistry'].unique()) == 1:
        p += plotnine.guides(shape="none")
    p.draw(show=True)
    p.save(output_figure_path, dpi=300)
    output_name_csv = Path(arguments.dir_out, 'aggregated_boxplot_stats.csv')
    with open(output_name_csv, "w") as handle:
        metrics_df.to_csv(handle, sep=';', index=False, header=list(metrics_df.columns))
    return {'graph_boxplot': output_figure_path}


def _calculate_auc_from_subtable(auprc_table: pd.DataFrame, parameter: str, threshold: float) -> float:
    """
    Calculates the Area Under the PR curve for a specified table.
    :param auprc_table: AUPRC table
    :param parameter: Parameter to subset from the AUPRC table (coverage or identity)
    :param threshold: Threshold for subsetting input table
    :return: AUC value
    """
    subtable = auprc_table[auprc_table[parameter] == threshold]
    precision_vector = np.r_[subtable['Precision'], 1, 0]
    recall_vector = np.r_[subtable['Recall'], 0, 1]
    sorted_index = np.argsort(precision_vector)
    pres_list_sorted = np.array(precision_vector)[sorted_index]
    rec_list_sorted = np.array(recall_vector)[sorted_index]
    return auc(pres_list_sorted, rec_list_sorted)


def _retrieve_precision_recall_files(arguments: argparse.Namespace,
                                     datasets_configuration: dict | None = None) -> pd.DataFrame:
    """
    Retrieves all precision recall files (*_precision_recall_*.tsv) from the input directory.
    :param arguments: Command line arguments
    :param datasets_configuration: Corresponding mock data names to clean names
    :return: All results stored in pd dataframe
    """
    range_thresholds = list(range(50, 105, 5))
    report_directory = Path(f'reporter_{arguments.type}')
    pr_files = glob.glob(str(Path(arguments.dir_in) / '*' / report_directory / '*_precision_recall*'))
    output_auprc_table = []
    mock_name_correspondence = {}
    if datasets_configuration is not None:
        mock_name_correspondence = {name: datasets_configuration[name]['clean_name'] for name in
                                    datasets_configuration.keys()}

    with open(Path(arguments.dir_out) / 'auprc.tsv', 'a') as output_file:
        for table in [Path(x) for x in pr_files]:
            input_table = pd.read_csv(table, header=0, sep=';')
            input_table[['Coverage_threshold', 'Identity_threshold']] = (
                input_table[['Coverage_threshold', 'Identity_threshold']].apply(pd.to_numeric))
            level = input_table['level'][0]
            tool = table.stem.split('_')[0]
            if tool in arguments.list_of_tools:
                dataset = table.parent.parent.stem
                try:
                    dataset = mock_name_correspondence[dataset]
                except KeyError:
                    pass
                for threshold in range_thresholds:
                    auc_coverage = _calculate_auc_from_subtable(input_table, 'Coverage_threshold', threshold)
                    auc_identity = _calculate_auc_from_subtable(input_table, 'Identity_threshold', threshold)

                    output_file.write(f'{tool}\t{auc_coverage}\tcoverage\t{threshold}\t{level}\t{dataset}\n')
                    output_file.write(f'{tool}\t{auc_identity}\tidentity\t{threshold}\t{level}\t{dataset}\n')
                    output_auprc_table.append([tool, auc_coverage, 'Coverage', threshold, level, dataset])
                    output_auprc_table.append([tool, auc_identity, 'Identity', threshold, level, dataset])

    auprc_dataframe = pd.DataFrame(output_auprc_table)
    if auprc_dataframe.empty:
        return auprc_dataframe
    auprc_dataframe.columns = ['tool', 'auc', 'stat', 'threshold', 'level', 'dataset']
    auprc_dataframe["threshold"] = pd.to_numeric(auprc_dataframe["threshold"])
    try:
        auprc_dataframe["dataset"] = auprc_dataframe["dataset"].apply(lambda x: mock_name_correspondence[x])
    except KeyError:
        pass
    return auprc_dataframe


def _plot_auprc_values(df_auprc: pd.DataFrame, arguments: argparse.Namespace) -> dict[str, list]:
    """
    Plots AUPRC for all datasets facetted by levels (gene or allele).
    :param df_auprc: pandas dataframe of auprc values
    :param arguments: Command line arguments
    :return: Dict with plot locations
    """
    output_dictionary = {'graph_auprc': []}
    if df_auprc.empty:
        output_figure_path = Path(arguments.dir_out) / 'figures' / 'auprc.png'
        p = plotnine.ggplot(df_auprc)
        p += plotnine.annotate("text", x=1, y=1, label="No value available.")
        p.draw(show=True)
        p.save(output_figure_path, verbose=False, dpi=300)
        output_dictionary['graph_auprc'].append({'src': output_figure_path})
        return output_dictionary

    for dataset in set(df_auprc['dataset']):
        output_figure_path = Path(arguments.dir_out) / 'figures' / f'aggregated_auprc_{dataset}.png'
        sub_df = df_auprc[df_auprc['dataset'] == dataset]
        p = plotnine.ggplot(sub_df, plotnine.aes(x='threshold', color='tool', y='auc'))
        p += plotnine.geom_line()
        p += plotnine.theme(axis_text_x=plotnine.element_text(angle=45, hjust=1))
        p += plotnine.facet_grid("stat", "level")
        p += plotnine.scale_y_continuous(limits=(0, 1))
        p += plotnine.labs(title=f'Area Under the PR curve for sample {dataset}.')
        p.draw(show=True)
        p.save(output_figure_path, dpi=300)
        output_dictionary['graph_auprc'].append({'src': output_figure_path})
    return output_dictionary


def _f1_score(pandas_row: pd.Series) -> float:
    """
    Calculates F1 score.
    :param pandas_row: row with precision and recall values
    :return: F1 score or 0 if ZeroDivisionError
    """
    try:
        score = 2 / (pandas_row['precision'] ** -1 + pandas_row['recall'] ** -1)
        return score
    except ZeroDivisionError:
        return 0.0


def _compute_mean_value_across_datasets(arguments: argparse.Namespace) -> pd.DataFrame:
    """
    Computes the mean auprc values for each tool across all datasets per threshold.
    :param arguments: Command line arguments
    :return: dataframe with mean values of metrics
    """
    range_thresholds = list(range(50, 105, 5))
    directory_report = Path(f'reporter_{arguments.type}')
    pr_files = glob.glob(str(Path(arguments.dir_in) / '*' / directory_report / '*_precision_recall*'))
    pr_table_list_for_df = []
    for pr_table in [Path(pr_file_path) for pr_file_path in pr_files]:
        tool = pr_table.stem.split('_')[0]
        if tool in arguments.list_of_tools:
            dataset = pr_table.parent.parent.stem
            with open(pr_table) as handle:
                pr_table_list_for_df.extend(
                    [f'{line.strip()};{tool};{dataset}'.split(";") for line in handle.readlines()[1:]])
    pr_table_df = pd.DataFrame(pr_table_list_for_df, columns=['precision', 'recall', 'coverage_threshold',
                                                              'identity_threshold', 'level', 'tool', 'dataset'])
    pr_table_df[['coverage_threshold', 'identity_threshold', 'precision', 'recall']] = (
        pr_table_df[['coverage_threshold', 'identity_threshold', 'precision', 'recall']].apply(pd.to_numeric))

    mean_metrics_list_for_df = []
    for id_threshold in range_thresholds:
        for cov_threshold in range_thresholds:
            subtable_to_consider = pr_table_df[(pr_table_df['coverage_threshold'] == cov_threshold) &
                                               (pr_table_df['identity_threshold'] == id_threshold)]
            for level in ['gene']:
                subtable_level = subtable_to_consider[subtable_to_consider['level'] == level]
                subtable_level['f1'] = subtable_level.apply(_f1_score, axis=1)
                for tool in set(subtable_level['tool']):
                    tmp_list = [tool]
                    for metric in ['precision', 'recall', 'f1']:
                        table_description = subtable_level[subtable_level['tool'] == tool].describe()
                        tmp_list.extend([table_description[metric]['mean'],
                                         table_description[metric]['min'],
                                         table_description[metric]['max'],
                                         table_description[metric]['25%'],
                                         table_description[metric]['75%']])
                    tmp_list.extend([cov_threshold, id_threshold, level])

                    mean_metrics_list_for_df.append(tmp_list)

    final_mean_metrics_df = pd.DataFrame(mean_metrics_list_for_df,
                                         columns=['tool', 'Precision', 'Precision_min', 'Precision_max', 'Precision_Q1',
                                                  'Precision_Q3',
                                                  'Recall', 'Recall_min', 'Recall_max', 'Recall_Q1', 'Recall_Q3',
                                                  'F1 score', 'F1 score_min', 'F1 score_max', 'F1 score_Q1',
                                                  'F1 score_Q3',
                                                  'coverage_threshold', 'identity_threshold',
                                                  'level'])
    final_mean_metrics_df.to_csv(str(Path(arguments.dir_out) / 'mean_values.csv'))
    return final_mean_metrics_df


def _plot_mean_values(df_mean: pd.DataFrame, arguments: argparse.Namespace) -> dict[str, Path]:
    """
    Plots mean metrics values for each tool across all datasets per threshold
    :param df_mean: dataframe containing the mean values
    :param arguments: Command line arguments
    :return: Dictionary with graph path
    """
    precision_table = df_mean[
        ['tool', 'Precision', 'Precision_min', 'Precision_max', 'Precision_Q1', 'Precision_Q3', 'coverage_threshold',
         'identity_threshold', 'level']]
    precision_table = precision_table.rename(
        columns={'Precision_Q1': 'Q1', 'Precision_Q3': 'Q3', 'Precision_min': 'min', 'Precision_max': 'max'})
    melted_precision_table = precision_table.melt(
        id_vars=['tool', 'level', 'coverage_threshold', 'identity_threshold', 'Q1', 'Q3', 'min', 'max'],
        value_vars=['Precision'])
    recall_table = df_mean[
        ['tool', 'Recall', 'Recall_min', 'Recall_max', 'Recall_Q1', 'Recall_Q3', 'coverage_threshold',
         'identity_threshold', 'level']]
    recall_table = recall_table.rename(
        columns={'Recall_Q1': 'Q1', 'Recall_Q3': 'Q3', 'Recall_min': 'min', 'Recall_max': 'max'})
    melted_recall_table = recall_table.melt(
        id_vars=['tool', 'level', 'coverage_threshold', 'identity_threshold', 'Q1', 'Q3', 'min', 'max'],
        value_vars=['Recall'])
    f1_table = df_mean[
        ['tool', 'F1 score', 'F1 score_min', 'F1 score_max', 'F1 score_Q1', 'F1 score_Q3', 'coverage_threshold',
         'identity_threshold', 'level']]
    f1_table = f1_table.rename(
        columns={'F1 score_Q1': 'Q1', 'F1 score_Q3': 'Q3', 'F1 score_min': 'min', 'F1 score_max': 'max'})
    melted_f1_table = f1_table.melt(
        id_vars=['tool', 'level', 'coverage_threshold', 'identity_threshold', 'Q1', 'Q3', 'min', 'max'],
        value_vars=['F1 score'])
    melted_mean_df = pd.concat([melted_precision_table, melted_recall_table, melted_f1_table])
    if melted_mean_df.empty:
        output_figure_path = Path(arguments.dir_out) / 'figures' / 'aggregated_mean_values.png'
        p = plotnine.ggplot(melted_mean_df)
        p += plotnine.annotate("text", x=1, y=1, label="No value available.")
        p.draw(show=True)
        p.save(output_figure_path, verbose=False)
        return {'graph_mean_values': output_figure_path}

    melted_mean_df['value'] = melted_mean_df['value'].apply(pd.to_numeric)
    melted_mean_df['Q1'] = melted_mean_df['Q1'].apply(pd.to_numeric)
    melted_mean_df['Q3'] = melted_mean_df['Q3'].apply(pd.to_numeric)
    color_scheme_tool = [['#c6dbef', '#4292c6', '#08306b'],
                         ['#c7e9c0', '#41ab5d', '#00441b'],
                         ['#d9d9d9', '#737373', '#000000'],
                         ['#fdd0a2', '#f16913', '#7f2704'],
                         ['#dadaeb', '#807dba', '#3f007d']]
    for identity_percentage in [50, 60, 70, 80, 90, 100]:
        output_figure_path = Path(arguments.dir_out) / 'figures' / f'aggregated_mean_values_{identity_percentage}.png'
        sub_df = melted_mean_df[(melted_mean_df['identity_threshold'] == identity_percentage)]
        variable_categorical = pd.Categorical(sub_df['variable'], categories=['Precision', 'Recall', 'F1 score'])
        sub_df = sub_df.assign(variable=variable_categorical)
        sub_df["variable"] = sub_df["variable"].cat.reorder_categories(["Precision", "Recall", "F1 score"])
        p = plotnine.ggplot(sub_df, plotnine.aes(x='coverage_threshold', y='value', fill='tool'))
        p += plotnine.geom_ribbon(plotnine.aes(ymin='min', ymax='max'),
                                  alpha=0.7)
        p += plotnine.scale_fill_manual(values=[x[0] for x in color_scheme_tool])
        p += plotnine.geom_ribbon(plotnine.aes(ymin='Q1', ymax='Q3'),
                                  alpha=0.7)
        p += plotnine.scale_fill_manual(values=[x[1] for x in color_scheme_tool])
        p += plotnine.geom_line(plotnine.aes(color='tool'))
        p += plotnine.scale_color_manual(values=[x[2] for x in color_scheme_tool])
        p += plotnine.theme(axis_text_x=plotnine.element_text(angle=45, hjust=1))
        p += plotnine.aes(ymin=0, ymax=1)
        p += plotnine.facet_grid("variable", "tool")
        p += plotnine.guides(color="none")
        p += plotnine.labs(title='Aggregated mean metrics values across all datasets.',
                           subtitle=f'Identity threshold = {identity_percentage}%', x='Coverage threshold')
        p.draw(show=True)
        p.save(output_figure_path, dpi=300)
    return {'graph_mean_values': Path(arguments.dir_out) / 'figures' / 'aggregated_mean_values_90.png'}


def _generate_aggregated_report(graph_dict: dict[str, Union[Path, list[dict[str, Path]]]], output_html: Path) -> None:
    """
    Generates the per sample report based on the jinja template.
    :param graph_dict: statistics dictionary
    :param output_html: Path to the HTML output report file
    :return: None
    """
    env = Environment(loader=FileSystemLoader(REPORT_AGG_TEMPLATE))
    template = env.get_template('aggregated_template.jinja')
    html_path = Path(output_html.parent.resolve())
    text_report = template.render(title="Aggregated report",
                                  graph_boxplot=graph_dict['graph_boxplot'].relative_to(html_path),
                                  graph_mean_values=graph_dict['graph_mean_values'].relative_to(html_path),
                                  graph_auprc=[{'src': p['src'].relative_to(html_path)}
                                               for p in graph_dict['graph_auprc']])
    with open(output_html, 'w') as handle:
        handle.write(text_report)


def main() -> None:
    """
    Runs the aggregated reporter.
    :return: None
    """
    initialize_logging()
    logging.info("Starting aggregated reporter script.")

    # Parse the command line arguments
    args = _parse_arguments()

    if not args.dir_out.exists():
        args.dir_out.mkdir(parents=True)

    dataset_config = load_dataset_config()

    statistics_table = _retrieve_statistics_information(args, dataset_config)
    boxplot_plot_dictionary = _plot_aggregated_metrics_boxplot(statistics_table, args)

    precision_recall_table = _retrieve_precision_recall_files(args, dataset_config)
    auprc_plot_dictionary = _plot_auprc_values(precision_recall_table, args)

    mean_metrics_table = _compute_mean_value_across_datasets(args)
    mean_metrics_plot_dictionary = _plot_mean_values(mean_metrics_table, args)

    complete_dictionary = {**boxplot_plot_dictionary, **auprc_plot_dictionary, **mean_metrics_plot_dictionary}
    _generate_aggregated_report(complete_dictionary, Path(args.dir_out) / 'report.html')


if __name__ == "__main__":
    main()
